### ISSUE TITLE
enable-fips doesn't work on bionic

### ISSUE THREAD

**Issue by cjohnston1158** [canonical/ubuntu-advantage-client#1300] opened 2021-01-12 17:19 UTC
`$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"`

`$ sudo ua enable-fips TOKEN
Sorry, but Canonical FIPS 140-2 Modules is not supported on bionic`
`$ sudo ua enable-fips-updates TOKEN
Sorry, but Canonical FIPS 140-2 Modules is not supported on bionic
`

FIPS is supported on bionic now. Either the client should be able to enable it, or the tool should state that it isn't able to and point people to the correct instructions.

**Comment by mitechie** [comment] 2021-01-12 19:49
I'm marking this a dupe of the v26 ua client release that's working on a beta this week that supports FIPS on bionic and xenial. This is part of: https://github.com/canonical/ubuntu-advantage-client/issues/1266 where we'll be bringing to conclusion the milestone v26 - FIPS 
https://github.com/canonical/ubuntu-advantage-client/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v26+-+FIPS%22

**Comment by mitechie** [comment] 2021-01-12 20:17
FTR I tested the FIPS support for bionic using the current daily PPA build:
https://launchpad.net/~canonical-server/+archive/ubuntu/ua-client-daily

This is not suitable for production but does function. 
Reproduction steps
- boot a bionic system (I tested with MAAS)
- add the PPA and upgrade the ua client
- attach the token for the subscription
- ua disable livepatch (livepatch does not make sense with a FIPS certified kernel)
- ua enable FIPS --beta
- <reboot host system>

    ua status --all
    ...
    fips          yes       enabled   NIST-certified FIPS modules

**Comment by mitechie** [comment] 2021-01-15 13:58
Version 26.0 beta up for testing in ppa:uaclient/staging.

We will be undergoing testing of this beta release over the next few days before ultimately publishing it to ppa:uaclient/stable.

To test this beta release on your favorite platform/vm/container of choice:

    sudo add-apt-repository ppa:ua-client/staging
    sudo apt-get updatesudo apt-get install ubuntu-advantage-tools # and ubuntu-advantage-pro if on a PRO image

    # obtain an Ubuntu Advantage token from https://ubuntu.com/advantage "Get your free token"
    sudo ua attach <YOUR_TOKEN>

    # disable livepatch since a FIPS kernel is certified and static and not able to livepatch without working around the certification. 
    sudo ua disable livepatch
    sudo ua enable fips --beta
    <reboot system to get new kernel>
    uname -r

**Comment by blackboxsw** [comment] 2021-01-29 03:08
Closed as this is a duplicate and ppa:ua-client/staging and ppa:canonical-server/ua-client-daily both contain functional new ua client that supports fips enablement

**Closed by blackboxsw** 2021-01-29 03:08 UTC
