### ISSUE TITLE
trusty -> xenial upgrade prompt due to local changes in /etc/apt/apt.conf.d/50unattended-upgrades

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1230] opened 2020-11-02 22:40 UTC
@OddBloke ran into this upgrade prompt on [ec2 trusty -> xenial](https://gist.github.com/OddBloke/5032777319bb14534c84b96401be3472#file-issue-md)

When performing a `do-release-upgrade` in a trusty container, I am prompted because `/etc/apt/apt.conf.d/50unattended-upgrades` "has been locally modified". This is the diff I'm presented with:

```diff
--- /etc/apt/apt.conf.d/50unattended-upgrades root.root 0644 2017-05-08 19:21:39
+++ /etc/apt/apt.conf.d/50unattended-upgrades.ucftmp root.root 0644 2020-02-17 18:03:38
@@ -1,11 +1,13 @@
 // Automatically upgrade packages from these (origin:archive) pairs
 Unattended-Upgrade::Allowed-Origins {
+ "${distro_id}:${distro_codename}";
 "${distro_id}:${distro_codename}-security";
 // Extended Security Maintenance; doesn't necessarily exist for
 // every release and this system may not have it installed, but if
 // available, the policy for updates is such that unattended-upgrades
 // should also install from here by default.
- "${distro_id}ESM:${distro_codename}";
+ "${distro_id}ESMApps:${distro_codename}-apps-security";
+ "${distro_id}ESM:${distro_codename}-infra-security";
 // "${distro_id}:${distro_codename}-updates";
 // "${distro_id}:${distro_codename}-proposed";
 // "${distro_id}:${distro_codename}-backports";
 ```

This may be related to an incomplete backport of unattended-upgrades conf file changes that only went back as far as xenial in
[LP: #1857051](https://bugs.launchpad.net/ubuntu/+source/unattended-upgrades/+bug/1857051)

**Comment by blackboxsw** [comment] 2020-11-02 23:11
This appears to be related to `ucf` and `ucfr` processing of 50unattended-upgrades file which should have registered a valid md5sum of this config file on trusty.??? Will check w/ @mvo5 on this, it seems that trusty doesn't have ucf management/registry of
  /etc/apt/apt.conf.d/50unattended-upgrades root.root  so I'm not certain what facilities there are to account for this across an LTS upgrade path

**Comment by mitechie** [comment] 2021-03-05 15:31
Isn't this related to work that's currently in progress to SRU the md5 sums? @lucasmoura ?

**Comment by lucasmoura** [comment] 2021-03-08 13:36
Yes, it is.

The SRU package was already uploaded into xenial-proposed, as can be seen in the SRU bug:
https://bugs.launchpad.net/ubuntu/+source/unattended-upgrades/+bug/1915547

I will be performing the extra test steps now to ensure that it is okay using it

**Comment by blackboxsw** [comment] 2021-03-24 02:20
I just set verification-done tag on https://bugs.launchpad.net/ubuntu/+source/unattended-upgrades/+bug/1915547 might need to tall to robiebasak again to see if this is settled

**Comment by lucasmoura** [comment] 2021-03-25 14:11
@blackboxsw I can confirm that the SRU package has landed in `xenial-updates` and I cannot reproduce that error anymore when upgrading from trusty to xenial

**Closed** 2021-04-07 19:05 UTC
