### ISSUE TITLE
apt-cache policy can return errors about file corruption if apt-get update in progress

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1361] opened 2021-02-08 18:40 UTC
During `ua enable fips --assume-yes` I got the error below. We retry 3 times on apt errors, but it would be better to not to also dump a traceback during those retries to make our logs more readable.

2021-02-08 18:37:08,808 - util.py:(550) [DEBUG]: Failed running command 'apt-cache policy' [exit(100)]. Message: E: Problem renaming the file /var/cache/apt/pkgcache.bin.WhYB9b to /var/cache/apt/pkgcache.bin - rename (2: No such file or directory)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted
 Retrying 3 more times.
2021-02-08 18:37:11,206 - util.py:(506) [DEBUG]: Ran cmd: apt-get update, rc: 0 stderr: b''
2021-02-08 18:37:11,208 - cli.py:(968) [ERROR]: Unhandled exception, please file a bug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 937, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 993, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 153, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 136, in new_f
    retval = f(args, cfg, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 696, in action_auto_attach
    token = _get_contract_token_from_cloud_identity(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 664, in _get_contract_token_from_cloud_identity
    if _detach(cfg, assume_yes=True) != 0:
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 594, in _detach
    ent.disable(silent=True)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 128, in disable
    if not handle_message_operations(msg_ops):
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 445, in handle_message_operations
    if not functor(**args):
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 414, in prompt_for_confirmation
    value = input(msg)
EOFError: EOF when reading a line

**Comment by lucasmoura** [comment] 2021-02-18 15:25
@blackboxsw Do you think we should completely remove the traceback from the logs ? What do you think we have a system where on the first error, we print the traceback in the log, but on subsequent errors, we only print them in the log if the error is different ?

**Comment by mitechie** [comment] 2021-02-18 19:24
I'm not sure if this is worth doing. If we swallow on a retry how will we distinguish different reasons for that retry? Would we lose detail and cause different cases to all be classified as "failed, retried"? Given it is in logs is it harmful here to have the specific detail?

**Comment by mitechie** [comment] 2021-03-05 15:33
Reading this shouldn't we do better about detecting the current apt lock and erroring/or retrying more clearly tied to the direct lock existance?

**Comment by orndorffgrant** [comment] 2022-04-12 13:30
@blackboxsw Closing as we can't reproduce this anymore. Please re-open if you see this again.

**Closed by orndorffgrant** 2022-04-12 13:30 UTC
