### ISSUE TITLE
Ubuntu Pro 20.04 Azure - Livepatch is not available for kernel

### ISSUE THREAD

**Issue by adamday2** [canonical/ubuntu-advantage-client#1817] opened 2021-09-23 04:43 UTC
It appears that livepatch cannot currently be enabled on an Ubuntu Pro 20.04 Azure image.

According to https://wiki.ubuntu.com/Kernel/Livepatch, Ubuntu 20.04 supports the following kernels:
`generic, lowlatency, aws, azure, oem, gcp, gke, gkeop`, 
but when using an azure-based kernel, livepatch returns that it is unsupported.

## Environment

Using the following Azure image offering:

```
"plan_name": "pro-20_04-lts",
"plan_product": "0001-com-ubuntu-pro-focal",
"plan_publisher": "canonical"
```

ubuntu-advantage-tools version: (27.2.2~20.04.1)

## Steps for Recreation

`ua status`

```
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        yes       n/a       Common Criteria EAL2 Provisioning Packages
cis           yes       disabled  Center for Internet Security Audit Tools
esm-apps      yes       enabled   UA Apps: Extended Security Maintenance (ESM)
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       disabled  NIST-certified core packages
fips-updates  yes       disabled  NIST-certified core packages with priority security updates
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>

                Account: <>
           Subscription: <>
            Valid until: 9999-12-31 00:00:00+00:00
Technical support level: essential
```

`ua enable livepatch`
```
One moment, checking your subscription first
Livepatch is not available for kernel 5.8.0-1041-azure.
Supported flavors are: generic, lowlatency, oem, aws, gcp, gkeop.
```

Detaching and reattaching does not resolve the issue.

As a last-ditch effort, I changed over to a generic kernel with:

```sh
sudo apt install linux-virtual linux-cloud-tools-virtual
sudo apt purge linux*azure
sudo reboot
```

And found that I could then successfully enable livepatch.

**Comment by orndorffgrant** [comment] 2021-09-24 14:41
Thank you for the bug report @adamday2!

I will try to reproduce this. It is likely a bug in the kernel flavor list on the backend, but I'll confirm that first.

**Comment by orndorffgrant** [comment] 2021-09-24 16:24
Okay I was able to reproduce and confirm this issue. I've opened a bug on the backend project (https://github.com/CanonicalLtd/ua-contracts/issues/2422) and will leave this bug open until that one is resolved.

**Comment by adamday2** [comment] 2021-11-08 20:40
This appears to be resolved.

**Comment by orndorffgrant** [comment] 2021-11-08 21:04
Thanks for checking in on this! Yes it looks like the backend has been updated and I've confirmed that this is working on my end as well. I'll close this bug as well as the backend one.

**Closed by orndorffgrant** 2021-11-08 21:04 UTC
