### ISSUE TITLE
"Entitled: No" when ua status is used on Ubuntu Pro 18.04 for Azure

### ISSUE THREAD

**Issue by ariannalozano** [canonical/ubuntu-advantage-client#1740] opened 2021-07-19 16:41 UTC
When ua status is used on Ubuntu Pro 18.04 for Azure, fips-updates entitlement appears as "No". As seen here:

ua status

SERVICE       ENTITLED  STATUS    DESCRIPTION

cis                     yes       disabled  Center for Internet Security Audit Tools

esm-apps        yes       enabled   UA Apps: Extended Security Maintenance (ESM)

esm-infra         yes       enabled   UA Infra: Extended Security Maintenance (ESM)

fips                    yes       enabled   NIST-certified core packages

**fips-updates     no        —         NIST-certified core packages with priority security updates**

livepatch            yes       n/a       Canonical Livepatch service

**Comment by blackboxsw** [comment] 2021-07-19 22:23
Thank you for filing this bug: I was unable to reproduce this issue on Azure PRO 18.04

Can you please perform the following:
  1. ua version
  2. sudo ua status --format=json
  3. sudo grep Traceback /var/log/ubuntu-advantage.log
  4. uname -a

Results for launching latest Ubuntu PRO 18.04 on Azure:
```bash
ubuntu@pro-fips-18:~$ sudo ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cis           yes       disabled  Center for Internet Security Audit Tools
esm-apps      yes       enabled   UA Apps: Extended Security Maintenance (ESM)
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       disabled  NIST-certified core packages
fips-updates  yes       disabled  NIST-certified core packages with priority security updates
livepatch     yes       enabled   Canonical Livepatch service

Enable services with: ua enable <service>

                Account: 12aad61c-6de4-4e53-a6c6-5aff52a83777
           Subscription: 12aad61c-6de4-4e53-a6c6-5aff52a83777
            Valid until: 9999-12-31 00:00:00
Technical support level: essential
ubuntu@pro-fips-18:~$ sudo ua status --format=json | jq .
{
  "_doc": "Content provided in json response is currently considered Experimental and may change",
  "attached": true,
  "expires": "9999-12-31 00:00:00",
  "origin": "azure",
  "services": [
    {
      "name": "cis",
      "description": "Center for Internet Security Audit Tools",
      "entitled": "yes",
      "status": "disabled",
      "statusDetails": "CIS Audit is not configured",
      "description_override": null
    },
    {
      "name": "esm-apps",
      "description": "UA Apps: Extended Security Maintenance (ESM)",
      "entitled": "yes",
      "status": "enabled",
      "statusDetails": "UA Apps: ESM is active",
      "description_override": null
    },
    {
      "name": "esm-infra",
      "description": "UA Infra: Extended Security Maintenance (ESM)",
      "entitled": "yes",
      "status": "enabled",
      "statusDetails": "UA Infra: ESM is active",
      "description_override": null
    },
    {
      "name": "fips",
      "description": "NIST-certified core packages",
      "entitled": "yes",
      "status": "disabled",
      "statusDetails": "FIPS is not configured",
      "description_override": null
    },
    {
      "name": "fips-updates",
      "description": "NIST-certified core packages with priority security updates",
      "entitled": "yes",
      "status": "disabled",
      "statusDetails": "FIPS Updates is not configured",
      "description_override": null
    },
    {
      "name": "livepatch",
      "description": "Canonical Livepatch service",
      "entitled": "yes",
      "status": "enabled",
      "statusDetails": "",
      "description_override": null
    }
  ],
  "configStatus": "inactive",
  "configStatusDetails": "No Ubuntu Advantage operations are running",
  "notices": [],
  "techSupportLevel": "essential",
  "account": "12aad61c-6de4-4e53-a6c6-5aff52a83777",
  "account-id": "aA8mB9wC-iTuCt3GndThWLxOCaM7bSr6PN48HfESf0qM",
  "subscription": "12aad61c-6de4-4e53-a6c6-5aff52a83777",
  "subscription-id": "cAKKWeFFKfglYIMlnfhz-Egc9GXNqCjMc9CKVw9uqWZw"
}
ubuntu@pro-fips-18:~$ lsb_release -sc
bionic
ubuntu@pro-fips-18:~$ uname -r
5.4.0-1051-azure
```

**Comment by ariannalozano** [comment] 2021-07-20 13:24
Hi @blackboxsw, thank you for taking a look into this. The customer I am speaking with just confirmed that they are instead running Ubuntu Pro FIPS 18.04 and not the standard Ubuntu Pro 18.04 image on Azure, which explains why FIPS updates shows up as not entitled. I apologize in advance for wasting your time on this.

**Comment by nmav** [comment] 2021-07-20 13:39
I do not think it is a waste of time. I'd expect fips-updates to be available on Ubuntu Pro FIPS

**Comment by ariannalozano** [comment] 2021-07-20 13:43
@nmav Does this mean that the customer should see that they are entitle to fips-updates on Ubuntu Pro FIPS 18.04 or is this something that we will be adding to Pro FIPS images?

**Comment by mitechie** [comment] 2021-07-20 13:43
We should be able to go from a FIPS system to a FIPS-updates system. I
assume this is confusion in the contract back end. Is this a custom
contract that would need to be updated with the contract service? Are
they using an old image before FIPS was fully supported?

Chad mentions he could not replicate this and requested customer
detailed information. it would still be helpful to get those so we can
investigate why this transition, which should be allowed and Chad
could not replicate with our current releases, is not being allowed
for the customer.

**Comment by ariannalozano** [comment] 2021-07-20 18:54
I have reached out to the customer to run steps 1-5 as per Chad's recommendation. I will follow-up here with more information on the output the customer is receiving. Thank you for your time in advance!

**Comment by orndorffgrant** [comment] 2021-11-17 14:16
Hi @ariannalozano I'm going to go ahead and close this, but if you have any more information or are still encountering this issue, please feel free to re-open it!

**Closed by orndorffgrant** 2021-11-17 14:16 UTC
