### ISSUE TITLE
apt list --upgradable is empty when post-update message told me to run it, update count is wrong

### ISSUE THREAD

**Issue by iainlane** [canonical/ubuntu-advantage-client#1548] opened 2021-04-13 16:20 UTC
I just **hacked this into the postinst for bionic**,  naively following the patterns for the other releases, to see what would happen. It mostly works, but I got the message:

```
9 additional updates are available with UA Apps: ESM.
To see these additional updates run: apt list --upgradable
See https://ubuntu.com/advantage or run: sudo ua status
```

but no updates are actually shown when I run this:

```
laney@bionic-vm:~$ apt list --upgradable
Listing... Done
laney@bionic-vm:~$
```

I then tested removing the `preferences.d` files to see if that was right, and I got **8** updates, not 9, so it seems the count is wrong in any event:

```
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
9 of the updates are from UA Apps: ESM.
...
The following packages will be upgraded:
  krb5-locales libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0 libopenjp2-7 libopenmpt0 libzmq5
```

Since I hacked this, that might be invalid, just thought I'd report for info. Feel free to close!

**Comment by orndorffgrant** [comment] 2022-01-05 14:18
Thanks for the bug report!

Since this is a nonstandard setup, and we are unable to reproduce, we are going to close this issue. Please reopen if you are still hitting this issue.

**Closed by orndorffgrant** 2022-01-05 14:18 UTC
