### ISSUE TITLE
cli: auto-completion shows a system command that does not exist

### ISSUE THREAD

**Issue by aciba90** [canonical/ubuntu-advantage-client#2279] opened 2022-10-04 15:04 UTC
```bash
lxc launch ubuntu-daily:kinetic dev-k && lxc shell dev-k

$ ua TAB
--debug          --version        attach           collect-logs     detach           enable           help             refresh          status           version          
--help           api              auto-attach      config           disable          fix              list             security-status  system

$ ua system
usage: pro <command> [flags]
argument : invalid choice: 'system' (choose from 'attach', 'api', 'auto-attach', 'collect-logs', 'config', 'detach', 'disable', 'enable', 'fix', 'security-status', 'help', 'refresh', 'status', 'version')

$ ua --version
27.11~22.10.1
```

**Comment by orndorffgrant** [comment] 2022-11-22 14:20
This is fixed in 27.12 :)

**Comment by renanrodrigo** [comment] 2022-11-24 00:24
Re-opening, as we realized this is unintended behavior

**Closed** 2022-11-30 16:40 UTC
