### ISSUE TITLE
http(s)_proxy environment settings not propagated to livepatch-client

### ISSUE THREAD

**Issue by tasdomas** [canonical/ubuntu-advantage-client#1664] opened 2021-06-03 10:54 UTC
ua client reacts to the `http_proxy`, `https_proxy`, `no_proxy` environment variables set when calling `ua attach`, however it does not propagate these settings to e.g. `canonical-livepatch`. This means that in a firewalled environment livepatch will fail to enable.

Ideally, when the proxy environment variables are set, ua client should call
```
canonical-livepatch config http_proxy=... https_proxy=....
```
Before enabling livepatch.

**Comment by mitechie** [comment] 2021-06-03 11:23
Thanks for the bug report. I'm going to mark this as a dupe of #1460. 

This work has started and will be in the next release of the ua tools.

**Closed by mitechie** 2021-06-03 11:23 UTC
