### ISSUE TITLE
Sudo required on Pro to make ua status --all show expected output

### ISSUE THREAD

**Issue by Hooloovoo** [canonical/ubuntu-advantage-client#1505] opened 2021-04-01 14:33 UTC
I just started a new 18.04 Pro gen2 VM on Azure and the initial output confused me. Running the command again with sudo then gave me what I expected and from then doing it without sudo was fine. 

Screenshot attached:
![unnamed](https://user-images.githubusercontent.com/556230/113309920-90e25580-92ff-11eb-93d1-3e91350884bb.png)

**Comment by Hooloovoo** [comment] 2021-04-07 20:33
Further testing with this shows more strange differences when using or not using sudo

```
$ ua version
26.2~16.04.1
```

![image](https://user-images.githubusercontent.com/556230/113929697-44f44c80-97e8-11eb-8272-400e7ec30132.png)

```
$ ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cis-audit     no        —         Center for Internet Security Audit Tools
esm-apps      yes       enabled   UA Apps: Extended Security Maintenance
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          yes       enabled   NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service
```

Running with sudo makes the cis line disappear

![image](https://user-images.githubusercontent.com/556230/113929864-7240fa80-97e8-11eb-995d-706a391218be.png)

```
$ sudo ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
esm-apps      yes       enabled   UA Apps: Extended Security Maintenance (ESM)
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       n/a       NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service
```

But running with --all shows it again and now the cis entitlement has changed:
![image](https://user-images.githubusercontent.com/556230/113929986-a0263f00-97e8-11eb-9b09-c1651bc7cfaa.png)

```
$ sudo ua status --all
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis           yes       disabled  Center for Internet Security Audit Tools
esm-apps      yes       enabled   UA Apps: Extended Security Maintenance (ESM)
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       n/a       NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service
```

**Comment by davecore82** [comment] 2021-04-07 21:02
Hi @Hooloovoo. I noticed too that it takes a while for the UA state to settle after launching an instance.  For about a minute after the instance is accessible, doing `ua status` shows this:

```
ubuntu@bionicprofips:~$ ua status
SERVICE       AVAILABLE  DESCRIPTION
esm-infra     yes        UA Infra: Extended Security Maintenance (ESM)
fips          yes        NIST-certified FIPS modules
fips-updates  yes        Uncertified security updates to FIPS modules
livepatch     yes        Canonical Livepatch service

This machine is not attached to a UA subscription.
See https://ubuntu.com/advantage
```

But after about a minute, the token attaches and then the output settles. Then it doesn't seem to change anymore whether you use sudo or not:

```
ubuntu@bionicprofips:~$ sudo ua status 
SERVICE       ENTITLED  STATUS    DESCRIPTION
esm-apps      yes       enabled   UA Apps: Extended Security Maintenance (ESM)
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       enabled   NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>

                Account: <redacted>
           Subscription: <redacted>
            Valid until: 9999-12-31 00:00:00
Technical support level: essential
```

Specifying `--all` will show you all services including the ones considered in beta like cis:

```
ubuntu@bionicprofips:~$ sudo ua status  --all
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        no        —         Common Criteria EAL2 Provisioning Packages
cis           yes       disabled  Center for Internet Security Audit Tools
esm-apps      yes       enabled   UA Apps: Extended Security Maintenance (ESM)
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       enabled   NIST-certified FIPS modules
fips-updates  no        —         Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>

                Account: <redacted>
           Subscription: <redacted>
            Valid until: 9999-12-31 00:00:00
Technical support level: essential
```

Would you agree with this or are you seeing something a different?

**Comment by blackboxsw** [comment] 2021-04-08 19:00
@davecore82 thanks for fielding this issue. sorry for radio silence here. @Hooloovoo images with 20.4 or later have a `ua status --wait` subcommand which will block until all setup config operations are complete. As I noticed in one of your screenshots, "Operation in progress" messages were listed in UA status.

So generally, I'd suggest blocking on `sudo ua status --wait`  until that comes back before assuming the system is up, attached and services enabled.   Known shortfall on certain PRO instances is extra setup time due to livepatch/core snap downloads https://github.com/canonical/ubuntu-advantage-client/issues/1502

**Comment by orndorffgrant** [comment] 2022-02-02 20:35
It appears that the original discrepancy noted here was due to auto-attach being in-progress.

I can no longer reproduce the "cis" vs "cis-audit" discrepancy - that should be fixed.

As for the general issue of non-root and root `ua status` output sometimes being different, we are tracking that in SC-708

So I'm going to go ahead and close this issue. If you disagree, feel free to reopen it :)

**Closed by orndorffgrant** 2022-02-02 20:35 UTC
